## Imports

In [14]:
#importing in the packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#importing warnings to turn off future warnings
import warnings
warnings.simplefilter(action='ignore')

## Clean data

In [15]:
#reading in the data
goodreads = pd.read_csv('good_reads_final.csv')
goodreads.head()

,author_average_rating,author_gender,author_genres,author_id,author_name,author_page_url,author_rating_count,author_review_count,birthplace,book_average_rating,book_fullurl,book_id,book_title,genre_1,genre_2,num_ratings,num_reviews,pages,publish_date,score
0,4.01,female,"historical-fiction,",74489,Victoria Thompson\n,/author/show/74489.Victoria_Thompson,74399,6268,United States\n,4.02,https://www.goodreads.com/book/show/686717.Mur...,686717,\n Murder on St. Mark's Place\n,Mystery,Historical,5260,375,277,2000,3230
1,4.15,male,"literature-fiction,mystery-thrillers,",706255,Stieg Larsson\n,/author/show/706255.Stieg_Larsson,3726435,142704,Sweden\n,4.13,https://www.goodreads.com/book/show/2429135.Th...,2429135,\n The Girl with the Dragon Tattoo\n,Fiction,Mystery,2229163,65227,465,August 2005,3062
2,4.00,female,"romance,",5618190,Mimi Jean Pamfiloff\n,/author/show/5618190.Mimi_Jean_Pamfiloff,76496,7975,United States\n,3.99,https://www.goodreads.com/book/show/27833684-t...,27833684,\n Tailored for Trouble\n,Romance,Contemporary,2151,391,354,2016,4585
3,3.88,male,"fiction,memoir,",37871,José Donoso\n,/author/show/37871.Jos_Donoso,5522,489,Chile\n,4.14,https://www.goodreads.com/book/show/382975.The...,382975,\n The Obscene Bird of Night\n,Fiction,Magical Realism,1844,173,438,1970,1533
4,4.10,female,"young-adult,fantasy,",36122,Patricia C. Wrede\n,/author/show/36122.Patricia_C_Wrede,291013,13453,United States\n,4.01,https://www.goodreads.com/book/show/64207.Sorc...,64207,\n Sorcery & Cecelia: or The Enchanted Ch...,Fantasy,Young Adult,17051,1890,326,April 15th 1988,2105

In [16]:
#Dropping the columns I know I won't be using
goodreads.drop(['author_page_url', 'book_fullurl', 'author_gender', 'author_genres', 'author_average_rating', 'author_id', 'birthplace', 'author_rating_count', 'author_review_count'], 1,  inplace=True)

In [17]:
goodreads.head()

,author_name,book_average_rating,book_id,book_title,genre_1,genre_2,num_ratings,num_reviews,pages,publish_date,score
0,Victoria Thompson\n,4.02,686717,\n Murder on St. Mark's Place\n,Mystery,Historical,5260,375,277,2000,3230
1,Stieg Larsson\n,4.13,2429135,\n The Girl with the Dragon Tattoo\n,Fiction,Mystery,2229163,65227,465,August 2005,3062
2,Mimi Jean Pamfiloff\n,3.99,27833684,\n Tailored for Trouble\n,Romance,Contemporary,2151,391,354,2016,4585
3,José Donoso\n,4.14,382975,\n The Obscene Bird of Night\n,Fiction,Magical Realism,1844,173,438,1970,1533
4,Patricia C. Wrede\n,4.01,64207,\n Sorcery & Cecelia: or The Enchanted Ch...,Fantasy,Young Adult,17051,1890,326,April 15th 1988,2105

In [18]:
#Dropping duplicates
goodreads = goodreads.drop_duplicates(subset ="book_title")
goodreads.head()

,author_name,book_average_rating,book_id,book_title,genre_1,genre_2,num_ratings,num_reviews,pages,publish_date,score
0,Victoria Thompson\n,4.02,686717,\n Murder on St. Mark's Place\n,Mystery,Historical,5260,375,277,2000,3230
1,Stieg Larsson\n,4.13,2429135,\n The Girl with the Dragon Tattoo\n,Fiction,Mystery,2229163,65227,465,August 2005,3062
2,Mimi Jean Pamfiloff\n,3.99,27833684,\n Tailored for Trouble\n,Romance,Contemporary,2151,391,354,2016,4585
3,José Donoso\n,4.14,382975,\n The Obscene Bird of Night\n,Fiction,Magical Realism,1844,173,438,1970,1533
4,Patricia C. Wrede\n,4.01,64207,\n Sorcery & Cecelia: or The Enchanted Ch...,Fantasy,Young Adult,17051,1890,326,April 15th 1988,2105

In [28]:
#Removing the \n's from the title column
goodreads['book_title'] = goodreads['book_title'].map(lambda cell: cell.replace("\n",""))
#Removing the \n's from the author column
goodreads['author_name'] = goodreads['author_name'].map(lambda cell: cell.replace("\n",""))
#Removing extra space from the title
goodreads['book_title'] = goodreads['book_title'].map(lambda cell: cell.strip())
#Removing extra space from the author
goodreads['author_name'] = goodreads['author_name'].map(lambda cell: cell.strip())

In [29]:
goodreads.head()

,author_name,book_average_rating,book_id,book_title,genre_1,genre_2,num_ratings,num_reviews,pages,publish_date,score
0,Victoria Thompson,4.02,686717,Murder on St. Mark's Place,Mystery,Historical,5260,375,277,2000,3230
1,Stieg Larsson,4.13,2429135,The Girl with the Dragon Tattoo,Fiction,Mystery,2229163,65227,465,August 2005,3062
2,Mimi Jean Pamfiloff,3.99,27833684,Tailored for Trouble,Romance,Contemporary,2151,391,354,2016,4585
3,José Donoso,4.14,382975,The Obscene Bird of Night,Fiction,Magical Realism,1844,173,438,1970,1533
4,Patricia C. Wrede,4.01,64207,Sorcery & Cecelia: or The Enchanted Chocolate Pot,Fantasy,Young Adult,17051,1890,326,April 15th 1988,2105

## Get unique genres

In [30]:
genre = goodreads['genre_1'].unique()
print(genre)

['Mystery' 'Fiction' 'Romance' 'Fantasy' 'Sequential Art' 'Young Adult'
 'Nonfiction' 'Paranormal' 'Historical' 'Science Fiction' 'Horror'
 'Classics' 'Autobiography' 'Womens Fiction' 'New Adult' 'Contemporary'
 'Humor' 'History' 'Childrens' 'Lgbt' 'Sports and Games' 'War' 'Dark'
 'Philosophy' 'Poetry' 'Christian' 'Adventure' 'Anthologies'
 'Christian Fiction' 'Warfare' 'Erotica' 'Biography' 'Adult Fiction'
 'Short Stories' 'Animals' 'Science' 'Shapeshifters' 'Self Help'
 'Politics' 'Music' 'Religion' 'Plays' 'Mental Health' 'Thriller' 'Crime'
 'Mythology' 'Travel' 'Military History' 'Language' 'Literature'
 'Psychology' 'Novels' 'Feminism' 'Economics' 'Business' 'Media Tie In'
 'World War II' 'Cultural' 'Science Fiction Fantasy' 'Death' 'Lds'
 'Northern Africa' 'Design' 'Magical Realism' 'Apocalyptic'
 'Realistic Fiction' 'Asian Literature' 'Spy Thriller' 'Suspense'
 'Holiday' 'Category Romance' 'Spirituality' 'Dungeons and Dragons'
 'Health' 'Education' 'Inspirational' 'Art' 'Amish' 'Did Not Finish'
 'Marriage' 'Family' 'Reference' 'Fan Fiction' 'Adult' 'Love' 'Epic'
 'Glbt' 'Sexuality' 'Parenting' 'Gardening' 'Literary Fiction' 'Sociology'
 'Westerns' 'Leadership' 'Eastern Africa' 'Food and Drink' 'Drama'
 'Novella' 'Biblical Fiction' 'Couture' 'Writing' 'Polyamorous'
 'Retellings' 'Football' 'European Literature' 'Medical' 'Comics' 'Occult'
 'Dark Fantasy' 'Speculative Fiction' 'Dc Comics' 'Unfinished' 'Esoterica'
 'Sports' 'Christianity' 'How To' 'Teaching' 'Social Science' 'Manga'
 'United States' 'Relationships' 'Pulp' 'Fairy Tales']

## Specify class-genre relationship

In [87]:
class1 = ['Fairy Tales','Fantasy','Childrens','Comics']
class2 = ['Science Fiction','Science Fiction Fantasy','Adventure', 'Fantasy','Fiction']
class3 = ['Science Fiction', 'Mystery','Suspense']
class4 = ['Nonfiction','Thriller','Crime','Paranormal']
class5 = ['Nonfiction','Science Fiction', 'Education', 'Science','Horror']
class6 = ['Romance','Horror','Nonfiction']
class7 = ['Philosophy','History','Historical', 'Classics','Nonfiction']
class8 = ['Nonfiction','Romance']
class9 = ['Poetry','History','Historical', 'Politics','Philosophy','Nonfiction','Classics']

In [88]:
class1_books = goodreads.loc[goodreads['genre_1'].isin(class1)]
class2_books = goodreads.loc[goodreads['genre_1'].isin(class2)]
class3_books = goodreads.loc[goodreads['genre_1'].isin(class3)]
class4_books = goodreads.loc[goodreads['genre_1'].isin(class4)]
class5_books = goodreads.loc[goodreads['genre_1'].isin(class5)]
class6_books = goodreads.loc[goodreads['genre_1'].isin(class6)]
class7_books = goodreads.loc[goodreads['genre_1'].isin(class7)]
class8_books = goodreads.loc[goodreads['genre_1'].isin(class8)]
class9_books = goodreads.loc[goodreads['genre_1'].isin(class9)]
class1_books_short = pd.DataFrame()
class2_books_short = pd.DataFrame()
class3_books_short = pd.DataFrame()
class4_books_short = pd.DataFrame()
class5_books_short = pd.DataFrame()
class6_books_short = pd.DataFrame()
class7_books_short = pd.DataFrame()
class8_books_short = pd.DataFrame()
class9_books_short = pd.DataFrame()

In [89]:
for i in class1: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class1_books_short = class1_books_short.append(j, ignore_index = True)
    
for i in class2: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class2_books_short = class2_books_short.append(j, ignore_index = True)
    
for i in class3: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class3_books_short = class3_books_short.append(j, ignore_index = True)

for i in class4: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class4_books_short = class4_books_short.append(j, ignore_index = True)
    
for i in class5: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class5_books_short = class5_books_short.append(j, ignore_index = True)
    
for i in class6: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class6_books_short = class6_books_short.append(j, ignore_index = True)
    
for i in class7: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class7_books_short = class7_books_short.append(j, ignore_index = True)

for i in class8: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class8_books_short = class8_books_short.append(j, ignore_index = True)
    
for i in class9: 
    j = goodreads.loc[goodreads['genre_1'] == i].sort_values(['genre_1','num_ratings'], ascending=[False, False]).drop_duplicates(['book_id']).reset_index(drop=True)
    j = j.head(5)
    class9_books_short = class9_books_short.append(j, ignore_index = True)

In [90]:
class1_books_short.to_csv('new_data/books_to_display/class1.csv')
class2_books_short.to_csv('new_data/books_to_display/class2.csv')
class3_books_short.to_csv('new_data/books_to_display/class3.csv')
class4_books_short.to_csv('new_data/books_to_display/class4.csv')
class5_books_short.to_csv('new_data/books_to_display/class5.csv')
class6_books_short.to_csv('new_data/books_to_display/class6.csv')
class7_books_short.to_csv('new_data/books_to_display/class7.csv')
class8_books_short.to_csv('new_data/books_to_display/class8.csv')
class9_books_short.to_csv('new_data/books_to_display/class9.csv')

In [91]:
class1_books.to_csv('new_data/books_by_class_genre/class1.csv')
class2_books.to_csv('new_data/books_by_class_genre/class2.csv')
class3_books.to_csv('new_data/books_by_class_genre/class3.csv')
class4_books.to_csv('new_data/books_by_class_genre/class4.csv')
class5_books.to_csv('new_data/books_by_class_genre/class5.csv')
class6_books.to_csv('new_data/books_by_class_genre/class6.csv')
class7_books.to_csv('new_data/books_by_class_genre/class7.csv')
class8_books.to_csv('new_data/books_by_class_genre/class8.csv')
class9_books.to_csv('new_data/books_by_class_genre/class9.csv')