# Imports

In [1]:
import pandas as pd
import csv
import numpy as np

%matplotlib inline

# Read in Files

In [14]:
books = pd.read_csv("books_final1.csv")
ratings = pd.read_csv("ratings.csv")

# Show Column Names

In [3]:
for col in books.columns: 
    print(col)

goodreads_book_id
tag_id
count
tag_name.x
genre.x
tag_name.y
genre.y
book_id
best_book_id
work_id
books_count
isbn
isbn13
authors
original_publication_year
original_title
title
language_code
average_rating
ratings_count
work_ratings_count
work_text_reviews_count
ratings_1
ratings_2
ratings_3
ratings_4
ratings_5
image_url
small_image_url

# Drop Unneded Columns

In [4]:
books.drop(['work_ratings_count', 'work_text_reviews_count','original_title','isbn13','small_image_url','ratings_1','ratings_2','ratings_3','ratings_4','ratings_5'],inplace=True, axis=1)

In [5]:
for col in books.columns: 
    print(col)

goodreads_book_id
tag_id
count
tag_name.x
genre.x
tag_name.y
genre.y
book_id
best_book_id
work_id
books_count
isbn
authors
original_publication_year
title
language_code
average_rating
ratings_count
image_url

# Deleting Not English Languages

In [6]:
books.language_code.unique()

array(['eng', 'en-US', nan, 'en-GB', 'en-CA', 'spa', 'fre', 'ger', 'ita',
       'mul', 'pol', 'por', 'per', 'vie', 'nl', 'rus', 'tur', 'ara',
       'rum', 'ind', 'jpn', 'fil', 'swe', 'nor', 'dan', 'en'],
      dtype=object)

In [7]:
books = books[books.language_code != 'spa']
books = books[books.language_code != 'fre']
books = books[books.language_code != 'ger']
books = books[books.language_code != 'ita']
books = books[books.language_code != 'mul']
books = books[books.language_code != 'pol']
books = books[books.language_code != 'por']
books = books[books.language_code != 'vie']
books = books[books.language_code != 'nl']
books = books[books.language_code != 'rus']
books = books[books.language_code != 'tur']
books = books[books.language_code != 'ara']
books = books[books.language_code != 'rum']
books = books[books.language_code != 'ind']
books = books[books.language_code != 'jpn']
books = books[books.language_code != 'fil']
books = books[books.language_code != 'swe']
books = books[books.language_code != 'nor']
books = books[books.language_code != 'dan']
books = books[books.language_code != 'per']
books = books[books.language_code != 'en']

In [8]:
books.language_code.unique()

array(['eng', 'en-US', nan, 'en-GB', 'en-CA'], dtype=object)

In [9]:
books = books.rename(columns = {'genre.x': 'genre_x', 'genre.y': 'genre_y', 'tag_name.x': 'tag_name_x',  'tag_name.y': 'tag_name_y'})

In [10]:
for col in books.columns: 
    print(col)

goodreads_book_id
tag_id
count
tag_name_x
genre_x
tag_name_y
genre_y
book_id
best_book_id
work_id
books_count
isbn
authors
original_publication_year
title
language_code
average_rating
ratings_count
image_url

# Genres of the Books

In [11]:
books.genre_x.unique()

array(['paranormal', 'scifi', 'fantasy', 'action', 'romance', 'mystery',
       'suspense', 'humour', 'adult', 'philosophy', 'historical',
       'nonfiction', 'literary-fiction', 'drama', 'horror', 'crime'],
      dtype=object)

In [12]:
books.tag_name_x.unique()

array(['paranormal', 'supernatural', 'sci-fi-fantasy', 'fantasy-sci-fi',
       'fantasy', 'adventure', 'romance', 'mystery', 'scifi-fantasy',
       'science-fiction-fantasy', 'sci-fi', 'fantasy-scifi', 'action',
       'thriller', 'science-fiction', 'humor', 'funny',
       'action-adventure', 'science', 'adult', 'adult-fiction', 'humour',
       'scifi', 'philosophy', 'history', 'nonfiction', 'historical',
       'non-fiction', 'historical-fiction', 'literary-fiction', 'drama',
       'thrillers', 'mystery-thriller', 'suspense', 'horror', 'crime',
       'detective', 'mysteries', 'mystery-crime', 'crime-mystery',
       'mystery-suspense', 'crime-fiction', 'suspense-thriller'],
      dtype=object)

In [13]:
books.head()

,goodreads_book_id,tag_id,count,tag_name_x,genre_x,tag_name_y,genre_y,book_id,best_book_id,work_id,books_count,isbn,authors,original_publication_year,title,language_code,average_rating,ratings_count,image_url
0,1,22973,673,paranormal,paranormal,paranormal,paranormal,27,1,41335427,275,439785960,"J.K. Rowling, Mary GrandPr√©",2005.0,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,1678823,https://images.gr-assets.com/books/1361039191m...
1,1,29011,484,supernatural,paranormal,supernatural,paranormal,27,1,41335427,275,439785960,"J.K. Rowling, Mary GrandPr√©",2005.0,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,1678823,https://images.gr-assets.com/books/1361039191m...
2,1,26785,1093,sci-fi-fantasy,scifi,sci-fi-fantasy,scifi,27,1,41335427,275,439785960,"J.K. Rowling, Mary GrandPr√©",2005.0,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,1678823,https://images.gr-assets.com/books/1361039191m...
3,1,11370,738,fantasy-sci-fi,fantasy,fantasy-sci-fi,fantasy,27,1,41335427,275,439785960,"J.K. Rowling, Mary GrandPr√©",2005.0,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,1678823,https://images.gr-assets.com/books/1361039191m...
4,1,11305,37174,fantasy,fantasy,fantasy,fantasy,27,1,41335427,275,439785960,"J.K. Rowling, Mary GrandPr√©",2005.0,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,1678823,https://images.gr-assets.com/books/1361039191m...

In [23]:
books['count'].sort_values(ascending = False)

23       47478
4364     41786
11964    39501
31       39330
41       38378
         ...
69227        1
69229        1
48881        1
52316        1
44264        1
Name: count, Length: 91310, dtype: int64

In [15]:
ratings.head()

   user_id  book_id  rating
0        1      258       5
1        2     4081       4
2        2      260       5
3        2     9296       5
4        2     2318       3

# Add ratings for books per user

In [16]:
book_ratings = pd.merge(ratings, books, on='book_id')

In [20]:
book_ratings.head(100)

,user_id,book_id,rating,goodreads_book_id,tag_id,count,tag_name.x,genre.x,tag_name.y,genre.y,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,258,5,1232,29076,230,suspense,suspense,suspense,suspense,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
1,1,258,5,1232,11305,796,fantasy,fantasy,fantasy,fantasy,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
2,1,258,5,1232,9886,143,drama,drama,drama,drama,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
3,1,258,5,1232,20994,254,mystery-thriller,mystery,mystery-thriller,mystery,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
4,1,258,5,1232,1659,214,adult-fiction,adult,adult-fiction,adult,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,362,258,2,1232,20989,122,mystery-suspense,mystery,mystery-suspense,mystery,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
96,362,258,2,1232,30358,311,thriller,suspense,thriller,suspense,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
97,362,258,2,1232,14552,122,history,historical,history,historical,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
98,362,258,2,1232,14487,2973,historical-fiction,historical,historical-fiction,historical,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...
99,362,258,2,1232,1642,315,adult,adult,adult,adult,...,263685,317554,24652,4789,11769,42214,101612,157170,https://images.gr-assets.com/books/1344545047m...,https://images.gr-assets.com/books/1344545047s...

In [24]:
book_ratings['book_id'].unique()

array([ 258, 4081,  260, ..., 9580, 8892, 9548])

# Keep one, most popular genre(based on tag count) genre for each book

In [29]:
explicit_ratings = book_ratings.sort_values(['book_id', 'count'], ascending=[True, False]).drop_duplicates(['book_id']).reset_index(drop=True)

In [31]:
explicit_ratings.head()

,user_id,book_id,rating,goodreads_book_id,tag_id,count,tag_name.x,genre.x,tag_name.y,genre.y,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,2886,1,5,2767052,11305,10836,fantasy,fantasy,fantasy,fantasy,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,4,2,5,3,11305,47478,fantasy,fantasy,fantasy,fantasy,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,451,3,5,41865,11305,14288,fantasy,fantasy,fantasy,fantasy,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,15,4,3,2657,14487,4735,historical-fiction,historical,historical-fiction,historical,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,4,5,4,4671,14487,2394,historical-fiction,historical,historical-fiction,historical,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [30]:
explicit_ratings.to_csv('explicit_ratings.csv')